NumPy (Numerical Python) is a Python library used for fast mathematical and numerical operations.
NumPy is a Python library that helps you work with arrays, matrices, and perform fast mathematical calculations.

Creating arrays (faster than Python lists)

Doing math operations (addition, multiplication, etc.)

Working with matrices

Handling large datasets

Used in Machine Learning, Data Science, AI

In [2]:
#importing numpy library
import numpy as np

In [6]:
#creating a simple array
arr = np.array([1,2,3,4,5])
print(arr) #printing the array
print(type(arr)) #printing the datatype

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#printing the first n numbers by using range
arr = np.arange(9)
print(arr)
type(arr)

[0 1 2 3 4 5 6 7 8]


numpy.ndarray

why do we need numpy when we already have list?
NumPy is faster, uses less memory, and supports vectorized mathematical operations.
Python lists are slow and not suitable for large numeric calculations.

In [ ]:
#Creating a Array
arr = np.array([1,2,3,4,5,6])
print(arr.ndim) #printing number of dimensions
print(arr.shape) #prints shape of array
print(len(arr)) #prints length
print(arr.dtype) #prints datatype int64  64 bits = 8 bytes
print(arr.itemsize) #prints each item has 8 bytes


1
(6,)
6
int64
8


In [ ]:
#2d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)#prints array
print(arr.ndim) #print dimension as 2
print(arr.shape) #print shape as (2,5) (rows,columns)
print(len(arr))#prints len as a 2
print(np.diag(arr)) #prints daignal [1,7]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
2
[1 7]


In [ ]:
#Functions for creating array
#printng ones in [rows,columns]
arr = np.ones((3,4)) 
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#printng zeros in[rows,columns]
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
#printing identity matrice with[4,4] matrice
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#printing identity matrice by given shape
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
#printing numbers in range
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#printng numbers in given range
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [ ]:
#printing numbers in given range with difference 2
arr = np.arange(1,9,2) #[start,end,step]
print(arr)

[1 3 5 7]


In [43]:
#printing random values with given shape
arr = np.random.random((2,3))
print(arr)

[[0.40720987 0.37234439 0.86249238]
 [0.31957248 0.71278556 0.03021037]]


In [47]:
arr = np.random.random((10,2))
print(arr)

[[0.46395213 0.60355028]
 [0.54112865 0.68922472]
 [0.263296   0.25451482]
 [0.27062476 0.95795833]
 [0.79328166 0.49691609]
 [0.38811552 0.60930312]
 [0.29560713 0.49531275]
 [0.20055093 0.70576538]
 [0.83693083 0.25653416]
 [0.50277798 0.07366437]]


In [ ]:
#prints 10 random numbers between 1 to 20
arr = np.random.randint(1,20,10)
print(arr)

[ 1 18 16 18  9  5  4 14  7  7]


In [ ]:
arr =np.random.randint(3,10)#prints one random b/w 3 and 10
print(arr)

4


Numpy indexing

In [67]:
#numpy indexing
arr =3 * np.arange(10)
print(arr)
print(arr[2])

[ 0  3  6  9 12 15 18 21 24 27]
6


In [69]:
print(arr[6])

18


In [78]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[0,3])

[[1 2 3 4]
 [5 6 7 8]]
4


In [ ]:
#replacing value in 2d array
arr[1,2] = 10
print(arr)

[[ 1  2  3  4]
 [ 5  6 10  8]]


Numpy Slicing

In [ ]:
#numpy slicing
arr = np.arange(10)
print(arr[::2])#[start:last:step] prints 0 2 4 6 8
print(arr[1:4])#[start:last] prints 1 2 3
print(arr[0:-4])#it will print upto 5



[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [89]:
#slicing on 3d array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:2,1:3]) #prints [2,3] and [6,7]
print(arr[:,1:3]) #prints [2 3] and [6 7] and [10 11]
print(arr[1:2,:])#prints [5 6 7 8]


[[2 3]
 [6 7]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[5 6 7 8]]


In [92]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr[2,1])# it prints 6
print(arr[[0,1,2],[0,1,0]]) # the answer will be in fromat fo[[0,0],[1,1],[2,0]] it prints 1 4 5

6
[1 4 5]


Numpy Maths

In [98]:
#Numpy maths
x = np.array([[1,2],[3,4]]) #created frist array
y = np.array([[5,6],[7,8]]) #created second array
print(np.add(x,y))#Adding two arrays
print('*'*20)
print(np.subtract(x,y))#subtracting two arrays
print('*'*20)
print(np.multiply(x,y))#Multiplying two arrays
print('*'*20)
print(np.divide(x,y))#dividing two arrays


[[ 6  8]
 [10 12]]
********************
[[-4 -4]
 [-4 -4]]
********************
[[ 5 12]
 [21 32]]
********************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [100]:
#Matrix multiplication
print(np.matmul(x,y)) #multiplication 
print(np.dot(x,y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [103]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))#prints sum of all elements in matrix
print(np.sum(x, axis =0)) #it will print sum of columns
print(np.sum(x,axis = 1))#it will return sum of rows

10
[4 6]
[3 7]


In [ ]:
print(np.min(x)) #prints minimum value in matrix
print(np.max(x)) #prints maximum value in matrix

1
4


In [109]:
#Transpose of matrix
print(x)
print("."*15)
print(x.T)

[[1 2]
 [3 4]]
...............
[[1 3]
 [2 4]]


In [ ]:
#exponential
np.exp(1)


np.float64(2.718281828459045)

In [112]:
np.exp(2)

np.float64(7.38905609893065)

NUMPY STATISTICS

In [ ]:
#Numpy statistics
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.max(x))#maximum
print(np.min(x))#minmum

10
1


In [ ]:
print(np.mean(x))#mean
print(np.median(x))#median
print(np.std(x))#standard deviation
print(np.var(x))#variance

5.5
5.5
2.8722813232690143
8.25


In [117]:
height = np.array([23,45,32,49])
weight = np.array([45,67,65,78])
np.corrcoef(height,weight)

array([[1.        , 0.91947512],
       [0.91947512, 1.        ]])